### ISSUE TITLE
Panicked at 'called `Option::unwrap()` on a `None`

### ISSUE THREAD

**Issue by rumatoest** [crossbeam-rs/crossbeam-utils#52]
Here is my code.
It actually works with crossbeam 0.3 but in 0.4 it fails with error in crossbeam_utils
```
  let ress = crossbeam::thread::scope(|scope| {
            (
                scope.spawn(move || lcam.capture_vec()),
                scope.spawn(move || rcam.capture_vec()),
            )
        });

        let frames = (
            ress.0.join().map_err(|e| format!("{:?}", e)).and_then(|r| r), // HERE I GETTING ERROR ON JOIN
            ress.1.join().map_err(|e| format!("{:?}", e)).and_then(|r| r),
        );
```

The stack trace 
```
stack backtrace:
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', libcore/option.rs:345:21

   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:511
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:426
   6: rust_begin_unwind
             at libstd/panicking.rs:337
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:92
   8: core::panicking::panic
             at libcore/panicking.rs:53
   9: <core::option::Option<T>>::unwrap
             at /checkout/src/libcore/macros.rs:20
  10: <crossbeam_utils::thread::ScopedJoinHandle<'a, T>>::join
             at /home/rumatoest/.cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-utils-0.5.0/src/thread.rs:369
  11: arcam::app::App::update
             at src/app.rs:89
```

**Comment by stjepang** [comment]
This code will not compile in the next version of `crossbeam-utils` because we don't allow moving the join handles out of the scope anymore. Threads can be joined only inside the scope.

**Comment by rumatoest** [comment]
Thanks. Well at least you should point out that in your documentation.
